apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: %NAMESPACE%
  name: web-tools
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: 'web-tools.oraybeta.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-tools
                port:
                  number: 3000

  tls:
    - hosts:
        - web-tools.oraybeta.com
      secretName: tls-oraybeta.com
